### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by SneumTV** [ledoge/dogegen#7]
When I try using the software in attempts to have it working with DisplayCAL, I get a connection failed error message:

```
> resolve_hdr
Attempting to connect to 127.0.0.1:20002
Failed to connect to server
>
```
I've tried using different commands and they all say the same, and I've also tried running the software as administrator to see if it would help with the issue. 
I'm not using any VPN or proxy on my system, and as I am unsure of how to use this software in the first place, I would like to know if I'm doing anything wrong and how I can fix it? 

![image](https://github.com/ledoge/dogegen/assets/168458586/d8a0ea6f-493b-4dac-861c-34e87befed8f)

Thank you in advance.

**Comment by ledoge** [comment]
Are you running that command after DisplayCAL prompts you to connect? As in, you first start the calibration/profiling process in DisplayCAL and you get the `Waiting for connection at [ip address]:20002` popup? If so, I'm not really sure why dogegen would fail to connect to it, but you could try connecting to the IP specified by DisplayCAL instead of the default `127.0.0.1` by doing `resolve_hdr [ip address]`.

**Comment by SneumTV** [comment]
I figured that out afterwards, but thanks for getting back to me! It seems like it worked like a charm!
![image](https://github.com/ledoge/dogegen/assets/168458586/b528a5d7-c9c1-4d48-b3d4-6dd1a3599dd2)

However, I have trouble validating the 3DLUT in DisplayCAL and it was rumored to be possible to do validation in HCFR, but I'm not sure how, at the way your software handles SDR and HDR in calibration (like Resolve) works really well! 
So far I've tried the ISO 12646:2008 testchart, but the ΔE is insanly high, but on the built in verify_video_extended_smpte2084_400_p3_2020.ti1 testchart the ΔE resembles what is to be considered good (average below 2, though max is 5.6). 

How do you validate your 3DLUTs after calibration?

**Comment by ledoge** [comment]
Personally, I've only used DisplayCAL for making and verifying 3D LUTs for SDR, since my LG OLED isn't very suited for 3D LUT calibration in HDR anyway. So unfortunately I don't know if/how you can do a proper verification in DisplayCAL, but I believe people usually use HCFR or ColorSpace ZRO instead.

**Comment by SneumTV** [comment]
I will give HCFR a go then, because the 3DLUT generated for my AW3225QF makes SDR look visibly similar to what it looks like on my SDR-calibration profile, and I am so excited to know if it is, as that could effectively be the beginning of the end of HDR struggles on Windows (if one is using your DWM_LUT GUI). 🎉
I'll let you know if my results are good - if they are, I'd like to share my findings in a video tutorial where I'll give you a shoutout (if that's okay with you of course) 🙏🏼
